Map on home page
FACN1/city-guide pull request #57
Opened 2017-05-01 16:28 UTC by Suuuuha

realted to #21

2017-05-01 16:34 UTC, Suuuuha commented
should add minZoom option to change the zoom when homepage first loads

2017-05-01 16:48 UTC, mattlub requested changes

2017-05-01 16:48 UTC, mattlub commented on app/public/index.html
> +    <title>city fucking Nuggets</title>
come on suha.

2017-05-01 16:48 UTC, mattlub commented on app/public/index.html
> +    <!-- <script src='https://api.mapbox.com/mapbox-gl-js/v0.35.1/mapbox-gl.js'></script> -->
remove this?

2017-05-01 16:48 UTC, mattlub commented on app/public/index.html
> +
two many empty spaces

2017-05-01 16:48 UTC, mattlub commented on app/public/main.css
> +.map {
this is not being used anywhere

2017-05-01 16:48 UTC, mattlub commented on app/public/main.css
> +  height: 500px;
make it full screen?

2017-05-01 16:48 UTC, mattlub commented on app/public/map.js
> +  maxZoom: 18,
remove max zoom from the tile layer?

2017-05-01 16:48 UTC, mattlub commented on app/public/map.js
> +  maxBounds: bounds
add a minzoom and maxzoom?

2017-05-02 07:54 UTC, Suuuuha commented on app/public/index.html
> +    <title>city fucking Nuggets</title>
sorry :roll_eyes:

2017-05-02 08:49 UTC, mattlub requested changes

2017-05-02 08:49 UTC, mattlub commented on app/public/index.html
> +    <title></title>
add a title!!!!

2017-05-02 08:49 UTC, mattlub commented on app/public/map.js
> +
put everything inside a immediately invoked function?

e.g. var map = (function() {
...
})();

2017-05-02 09:14 UTC, mattlub approved these changes

2017-05-02 09:23 UTC, merged