test the home page route
FACN1/city-guide pull request #64
Opened 2017-05-02 12:55 UTC by Suuuuha

2017-05-02 13:28 UTC, mattlub approved these changes

2017-05-02 15:18 UTC, Karyum commented on app/test/test.js
> +      // console.log(res)
do we need this console log here ?

2017-05-02 15:19 UTC, Karyum commented on app/test/test.js
>  tape('basic passing test, to check tape is functioning correctly', t => {
do you still need this test?

2017-05-02 15:21 UTC, Karyum requested changes
some small changes

2017-05-03 07:57 UTC, mattlub approved these changes

2017-05-03 07:57 UTC, Karyum approved these changes
FILEM

2017-05-03 08:00 UTC, merged