add functionality to tick and cross buttons on location selector
FACN1/city-guide pull request #78
Opened 2017-05-07 13:58 UTC by Suuuuha

related to #35

2017-05-07 14:34 UTC, Karyum commented on app/public/map.js
> +  var infoCrossBtn = document.querySelector('.location-select-cross')
maybe we should change the variable name to something else cause infoCrossBtn i might this it is the cross for the info tab

2017-05-07 14:38 UTC, Suuuuha commented on app/public/map.js
> +  var infoCrossBtn = document.querySelector('.location-select-cross')
can u write in english ?

2017-05-07 14:46 UTC, Suuuuha commented on app/public/map.js
> +  var infoCrossBtn = document.querySelector('.location-select-cross')
i guess u're right , changed it :+1:

2017-05-08 07:44 UTC, Karyum approved these changes

2017-05-08 08:11 UTC, mattlub commented on app/public/map.js
> +  var locationSelector = document.querySelector('.location-select-display')
why not call this locationSelectDisplay?

2017-05-08 09:06 UTC, mattlub requested changes
sorry for another change request 😁

2017-05-08 09:06 UTC, mattlub commented on app/public/index.html
> +    <div class="location-select-display visible">
shouldn't start visible right?

2017-05-08 13:38 UTC, Suuuuha commented on app/public/index.html
> +    <div class="location-select-display visible">
yeah it was there for testing and forgot to remove .. thnx

2017-05-08 14:08 UTC, mattlub approved these changes

2017-05-08 14:15 UTC, HilbertSpitzer approved these changes

2017-05-08 14:28 UTC, merged