setup image hosting using amazon
FACN1/city-guide pull request #82
Opened 2017-05-08 13:15 UTC by Suuuuha

related to #50

2017-05-08 13:17 UTC, Suuuuha commented
some notes: 
- all the class names will be changed when we have the form tab

2017-05-08 14:07 UTC, mattlub requested changes

2017-05-08 14:07 UTC, mattlub commented on app/public/map.js
> +    xhr.open('GET', `/sign-s3?file-name=${file.name}&file-type=${file.type}`)
es6...

2017-05-08 14:07 UTC, mattlub commented on app/public/map.js
> +  document.querySelector('.class-unknown').onchange = function () {
make this class name a bit clearer, 'image-input'?

2017-05-08 14:07 UTC, mattlub commented on app/public/map.js
> +      console.log('No file selected')
return here? probably don't want to log this either.

2017-05-08 14:07 UTC, mattlub commented on app/public/map.js
> +    const file = files[0]
what else is in the files array?

2017-05-08 14:07 UTC, mattlub commented on app/public/map.js
> +          console.log('Could not get signed URL.')
do something better or add a comment to say something better needs to be done.

2017-05-08 14:07 UTC, mattlub commented on app/public/map.js
> +          console.log('Could not upload file.')
do something better or add a comment to say something better needs to be done.

2017-05-08 14:21 UTC, Suuuuha commented on app/public/map.js
> +    const file = files[0]
for now theres nothing else cause we uploaded just 1 file

2017-05-09 08:19 UTC, mattlub requested changes

2017-05-09 08:19 UTC, mattlub commented on app/public/map.js
> +      // should send the user that he didn't uplaod a file or it wasn't succeful
need to return here or have an else block

2017-05-09 09:08 UTC, mattlub approved these changes

2017-05-09 09:10 UTC, Karyum approved these changes

2017-05-09 09:18 UTC, merged